### ISSUE TITLE
TheSportsDB Site updates

### ISSUE THREAD

**Issue by zag2me** [enen92/script.module.thesportsdb#1]
Just a few updates on the site to be aware of:

**Database Changes**
[Events] strRaceCircuit -> strCircuit
[Events] strRaceCity -> strCity
[Events] strRaceCountry -> strCountry

Hopefully these changes did not break anything, but I thought it was worth mentioning them.

**Artwork**
New artwork type 
[League] strPoster

**API Changes**
New API method for filename lookups
searchfilename.php

**Comment by enen92** [comment]
Thanks for the heads up. I'll have to rewrite this module completely because I have some projects in mind that use the bd.
My time at the moment is pretty limited but I'll try to find a gap to work on this soon enough
cheers

**Comment by zag2me** [comment]
No problem, there is another guy "prodigy4kstp01" looking to write a scraper as well, so I pointed him here for the module.

**Comment by enen92** [comment]
As I am writting this basically from scratch this issue no longer applies
